[package]
name = "mnt-token-rpc"
version = "0.5.0"
authors = ["Minterest developers"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0" }
jsonrpc-core = "15.0.0"
jsonrpc-core-client = "15.0.0"
jsonrpc-derive = "15.0.0"

sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5" }

mnt-token-rpc-runtime-api = { path = "runtime-api" }
minterest-primitives = { path = "../../../primitives" }
